# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Patricia Destriza\Desktop\CompStud Queuing System\ui\CSQueuingSystem.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ComputerStudiesQueuingSystem(object):
    def setupUi(self, ComputerStudiesQueuingSystem):
        ComputerStudiesQueuingSystem.setObjectName("ComputerStudiesQueuingSystem")
        ComputerStudiesQueuingSystem.resize(1000, 500)
        ComputerStudiesQueuingSystem.setMinimumSize(QtCore.QSize(1000, 500))
        ComputerStudiesQueuingSystem.setStyleSheet("background-color: rgb(0, 58, 108);")
        self.centralwidget = QtWidgets.QWidget(ComputerStudiesQueuingSystem)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.top_bar = QtWidgets.QFrame(self.centralwidget)
        self.top_bar.setMinimumSize(QtCore.QSize(0, 50))
        self.top_bar.setMaximumSize(QtCore.QSize(16777215, 40))
        self.top_bar.setStyleSheet("background-color: rgb(0, 58, 108);\n"
"")
        self.top_bar.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.top_bar.setFrameShadow(QtWidgets.QFrame.Plain)
        self.top_bar.setObjectName("top_bar")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.top_bar)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.toggle_button = QtWidgets.QFrame(self.top_bar)
        self.toggle_button.setMaximumSize(QtCore.QSize(70, 60))
        self.toggle_button.setStyleSheet("QPushButton:hover{\n"
"    background-color: rgb(85, 170, 255);\n"
"    border-radius: 15px\n"
"}")
        self.toggle_button.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.toggle_button.setFrameShadow(QtWidgets.QFrame.Plain)
        self.toggle_button.setObjectName("toggle_button")
        self.Btn_Toggle = QtWidgets.QPushButton(self.toggle_button)
        self.Btn_Toggle.setGeometry(QtCore.QRect(0, -20, 71, 81))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Btn_Toggle.sizePolicy().hasHeightForWidth())
        self.Btn_Toggle.setSizePolicy(sizePolicy)
        self.Btn_Toggle.setMinimumSize(QtCore.QSize(70, 60))
        self.Btn_Toggle.setMaximumSize(QtCore.QSize(250, 16777215))
        self.Btn_Toggle.setStyleSheet("QFrame{\n"
"    background-color: rgb(0, 58, 108);\n"
"}\n"
"QPushButton{\n"
"    padding: 5px 30px;\n"
"    border: none;\n"
"    background-color: rgb(0, 58, 108);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(85, 170, 255);\n"
"}\n"
"\n"
"")
        self.Btn_Toggle.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/cil-menu.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Btn_Toggle.setIcon(icon)
        self.Btn_Toggle.setIconSize(QtCore.QSize(24, 24))
        self.Btn_Toggle.setObjectName("Btn_Toggle")
        self.horizontalLayout.addWidget(self.toggle_button)
        self.frame_top = QtWidgets.QFrame(self.top_bar)
        self.frame_top.setStyleSheet("")
        self.frame_top.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_top.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_top.setObjectName("frame_top")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_top)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 5)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_7 = QtWidgets.QLabel(self.frame_top)
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_4.addWidget(self.label_7)
        self.label_9 = QtWidgets.QLabel(self.frame_top)
        self.label_9.setMaximumSize(QtCore.QSize(50, 40))
        self.label_9.setText("")
        self.label_9.setPixmap(QtGui.QPixmap("C:\\Users\\Patricia Destriza\\Desktop\\CompStud Queuing System\\ui\\../CS.png"))
        self.label_9.setScaledContents(True)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_4.addWidget(self.label_9)
        self.label_5 = QtWidgets.QLabel(self.frame_top)
        self.label_5.setMinimumSize(QtCore.QSize(200, 0))
        self.label_5.setMaximumSize(QtCore.QSize(900, 16777215))
        self.label_5.setStyleSheet("font: 75 14pt \"Century Gothic\";\n"
"color: rgb(255, 255, 255);")
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_4.addWidget(self.label_5)
        self.label_8 = QtWidgets.QLabel(self.frame_top)
        self.label_8.setText("")
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_4.addWidget(self.label_8)
        self.horizontalLayout.addWidget(self.frame_top)
        self.verticalLayout.addWidget(self.top_bar)
        self.content = QtWidgets.QFrame(self.centralwidget)
        self.content.setStyleSheet("background-color: rgb(226, 240, 255);")
        self.content.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.content.setFrameShadow(QtWidgets.QFrame.Plain)
        self.content.setObjectName("content")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.content)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_left_menu = QtWidgets.QFrame(self.content)
        self.frame_left_menu.setMinimumSize(QtCore.QSize(70, 0))
        self.frame_left_menu.setMaximumSize(QtCore.QSize(70, 16777215))
        self.frame_left_menu.setStyleSheet("QFrame{\n"
"    background-color: rgb(0, 58, 108);\n"
"}\n"
"QPushButton{\n"
"    padding: 20px 30px;\n"
"    border: none;\n"
"    background-color: rgb(0, 58, 108);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:pressed{\n"
"    border-bottom-color: rgb(85, 170, 255);\n"
"}\n"
"\n"
"")
        self.frame_left_menu.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_left_menu.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_left_menu.setObjectName("frame_left_menu")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_left_menu)
        self.verticalLayout_2.setContentsMargins(13, 10, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_for_buttons = QtWidgets.QFrame(self.frame_left_menu)
        self.frame_for_buttons.setMinimumSize(QtCore.QSize(70, 0))
        self.frame_for_buttons.setMaximumSize(QtCore.QSize(200, 16777215))
        self.frame_for_buttons.setStyleSheet("QPushButton:hover{\n"
"    background-color: rgb(85, 170, 255);\n"
"}\n"
"")
        self.frame_for_buttons.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_for_buttons.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_for_buttons.setObjectName("frame_for_buttons")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_for_buttons)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.prioritynumber_button = QtWidgets.QPushButton(self.frame_for_buttons)
        self.prioritynumber_button.setMinimumSize(QtCore.QSize(200, 0))
        self.prioritynumber_button.setMaximumSize(QtCore.QSize(250, 16777215))
        self.prioritynumber_button.setStyleSheet("background-image: url(:/icons/icons/cil-notes.png);\n"
"background-repeat:none;\n"
"padding-left:30px;\n"
"background-position: center left;\n"
"font: 75 9pt \"Century Gothic\";\n"
"")
        self.prioritynumber_button.setObjectName("prioritynumber_button")
        self.verticalLayout_3.addWidget(self.prioritynumber_button)
        self.room_reservation = QtWidgets.QPushButton(self.frame_for_buttons)
        self.room_reservation.setMinimumSize(QtCore.QSize(200, 0))
        self.room_reservation.setMaximumSize(QtCore.QSize(250, 16777215))
        self.room_reservation.setStyleSheet("background-image: url(:/icons/icons/cil-3d.png);\n"
"background-repeat:none;\n"
"padding-left:45px;\n"
"background-position: center left;\n"
"font: 75 9pt \"Century Gothic\";\n"
"")
        self.room_reservation.setObjectName("room_reservation")
        self.verticalLayout_3.addWidget(self.room_reservation)
        self.appointment_setter = QtWidgets.QPushButton(self.frame_for_buttons)
        self.appointment_setter.setMinimumSize(QtCore.QSize(200, 0))
        self.appointment_setter.setMaximumSize(QtCore.QSize(250, 16777215))
        self.appointment_setter.setStyleSheet("background-image: url(:/icons/icons/cil-pencil.png);\n"
"background-repeat:none;\n"
"padding-left:45px;\n"
"background-position: center left;\n"
"font: 75 9pt \"Century Gothic\";\n"
"")
        self.appointment_setter.setObjectName("appointment_setter")
        self.verticalLayout_3.addWidget(self.appointment_setter)
        self.special_services = QtWidgets.QPushButton(self.frame_for_buttons)
        self.special_services.setMinimumSize(QtCore.QSize(200, 0))
        self.special_services.setMaximumSize(QtCore.QSize(250, 16777215))
        self.special_services.setStyleSheet("background-image: url(:/icons/icons/cil-pin.png);\n"
"background-repeat:none;\n"
"padding-left:30px;\n"
"background-position: center left;\n"
"font: 75 9pt \"Century Gothic\";\n"
"")
        self.special_services.setObjectName("special_services")
        self.verticalLayout_3.addWidget(self.special_services)
        self.verticalLayout_2.addWidget(self.frame_for_buttons, 0, QtCore.Qt.AlignTop)
        self.horizontalLayout_2.addWidget(self.frame_left_menu)
        self.prio_queue_display = QtWidgets.QFrame(self.content)
        self.prio_queue_display.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.prio_queue_display.setFrameShadow(QtWidgets.QFrame.Plain)
        self.prio_queue_display.setObjectName("prio_queue_display")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.prio_queue_display)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frame = QtWidgets.QFrame(self.prio_queue_display)
        self.frame.setMinimumSize(QtCore.QSize(0, 10))
        self.frame.setMaximumSize(QtCore.QSize(16777215, 20))
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame.setObjectName("frame")
        self.verticalLayout_4.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(self.prio_queue_display)
        self.frame_2.setMaximumSize(QtCore.QSize(16777215, 80))
        self.frame_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.frame_6 = QtWidgets.QFrame(self.frame_2)
        self.frame_6.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout_3.addWidget(self.frame_6)
        self.label = QtWidgets.QLabel(self.frame_2)
        self.label.setMaximumSize(QtCore.QSize(360, 16777215))
        self.label.setStyleSheet("font: 75 40pt \"Century Gothic\";")
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.frame_7 = QtWidgets.QFrame(self.frame_2)
        self.frame_7.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_7.setObjectName("frame_7")
        self.horizontalLayout_3.addWidget(self.frame_7)
        self.verticalLayout_4.addWidget(self.frame_2)
        self.frame_5 = QtWidgets.QFrame(self.prio_queue_display)
        self.frame_5.setMinimumSize(QtCore.QSize(0, 20))
        self.frame_5.setMaximumSize(QtCore.QSize(16777215, 20))
        self.frame_5.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_4.addWidget(self.frame_5)
        self.frame_3 = QtWidgets.QFrame(self.prio_queue_display)
        self.frame_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.frame_8 = QtWidgets.QFrame(self.frame_3)
        self.frame_8.setMaximumSize(QtCore.QSize(350, 16777215))
        self.frame_8.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_8.setObjectName("frame_8")
        self.label_2 = QtWidgets.QLabel(self.frame_8)
        self.label_2.setGeometry(QtCore.QRect(100, 220, 151, 16))
        self.label_2.setStyleSheet("font: 75 14pt \"Century Gothic\";")
        self.label_2.setObjectName("label_2")
        self.textEdit = QtWidgets.QTextEdit(self.frame_8)
        self.textEdit.setGeometry(QtCore.QRect(60, 10, 221, 201))
        self.textEdit.setObjectName("textEdit")
        self.horizontalLayout_5.addWidget(self.frame_8)
        self.frame_9 = QtWidgets.QFrame(self.frame_3)
        self.frame_9.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_9.setObjectName("frame_9")
        self.label_3 = QtWidgets.QLabel(self.frame_9)
        self.label_3.setGeometry(QtCore.QRect(210, 180, 101, 21))
        self.label_3.setStyleSheet("font: 75 14pt \"Century Gothic\";")
        self.label_3.setObjectName("label_3")
        self.textEdit_4 = QtWidgets.QTextEdit(self.frame_9)
        self.textEdit_4.setGeometry(QtCore.QRect(340, 60, 104, 101))
        self.textEdit_4.setObjectName("textEdit_4")
        self.textEdit_2 = QtWidgets.QTextEdit(self.frame_9)
        self.textEdit_2.setGeometry(QtCore.QRect(100, 60, 104, 101))
        self.textEdit_2.setObjectName("textEdit_2")
        self.textEdit_3 = QtWidgets.QTextEdit(self.frame_9)
        self.textEdit_3.setGeometry(QtCore.QRect(220, 60, 104, 101))
        self.textEdit_3.setObjectName("textEdit_3")
        self.horizontalLayout_5.addWidget(self.frame_9)
        self.verticalLayout_4.addWidget(self.frame_3)
        self.frame_4 = QtWidgets.QFrame(self.prio_queue_display)
        self.frame_4.setMaximumSize(QtCore.QSize(16777215, 20))
        self.frame_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_4.addWidget(self.frame_4)
        self.horizontalLayout_2.addWidget(self.prio_queue_display)
        self.verticalLayout.addWidget(self.content)
        ComputerStudiesQueuingSystem.setCentralWidget(self.centralwidget)

        self.retranslateUi(ComputerStudiesQueuingSystem)
        QtCore.QMetaObject.connectSlotsByName(ComputerStudiesQueuingSystem)

    def retranslateUi(self, ComputerStudiesQueuingSystem):
        _translate = QtCore.QCoreApplication.translate
        ComputerStudiesQueuingSystem.setWindowTitle(_translate("ComputerStudiesQueuingSystem", "MainWindow"))
        self.label_5.setText(_translate("ComputerStudiesQueuingSystem", "Computer Studies Queuing System"))
        self.prioritynumber_button.setText(_translate("ComputerStudiesQueuingSystem", "PRIORITY NUMBER"))
        self.room_reservation.setText(_translate("ComputerStudiesQueuingSystem", "ROOM RESERVATION"))
        self.appointment_setter.setText(_translate("ComputerStudiesQueuingSystem", "APPOINTMENT SETTER"))
        self.special_services.setText(_translate("ComputerStudiesQueuingSystem", "SPECIAL SERVICES"))
        self.label.setText(_translate("ComputerStudiesQueuingSystem", "Priority Queue"))
        self.label_2.setText(_translate("ComputerStudiesQueuingSystem", "Current Number"))
        self.label_3.setText(_translate("ComputerStudiesQueuingSystem", "next in line"))
import resource_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ComputerStudiesQueuingSystem = QtWidgets.QMainWindow()
    ui = Ui_ComputerStudiesQueuingSystem()
    ui.setupUi(ComputerStudiesQueuingSystem)
    ComputerStudiesQueuingSystem.show()
    sys.exit(app.exec_())
